[package]
name = "sing"
version = "0.1.0"
authors = ["Haochuan Liu <haochuan.liu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.10"
clap = "2.33.0"
spinner = "0.5.0"
